# Generated by Django 5.2.7 on 2026-02-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_details_options_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe_details',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
