# Generated by Django 6.0.4 on 2026-04-16 07:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_details',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='recipe_img'),
        ),
    ]
